### ISSUE TITLE
Error when changing sessions directory

### ISSUE THREAD

**Issue by thepenguinthatwants** [hokorobi/vim-clap-sessions#1]
Hi!
Your plugin seems to suit my use well.

I added this line to my init.vim

let g:clap_session_dir = "~/.config/nvim/sessions/"

When I open nvim I get this error

E15: Invalid expression: "~/.config/nvim/sessions/"

Also when I tried to open 
`:Claps sessions`
it shows nothing.

**Comment by thepenguinthatwants** [comment]
Oooh so it was single quote

**Comment by hokorobi** [comment]
I tried to add the same settings, but didn't get an error?

**Comment by thepenguinthatwants** [comment]
I used double quotes and it was the problem. :D But its now solved thanks!
